development:
  adapter: mysql
  database: graham_dev
  username: root
  password: getset
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  database: graham_test
  username: root
  password: getset
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *TEST

production:
  adapter: mysql
  database: graham_pro
  username: root
  password: getset
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock
